## Preprocessing

In [21]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf
import numpy as np

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])

application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()

unique_values

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [7]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

replace_application_types = application_type_counts[application_type_counts < 500].index

application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(replace_application_types, 'Other')

application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_type_counts = application_df['APPLICATION_TYPE'].value_counts()
print(application_type_counts)

cutoff_value = 500

application_types_to_replace = application_type_counts[application_type_counts < cutoff_value].index.tolist()


# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [9]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

cutoff_value = 1000

classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls, "Other")
    
print(application_df['CLASSIFICATION'].value_counts())

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64
CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [10]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_counts)

filtered_classification_counts = classification_counts[classification_counts > 1]
print(filtered_classification_counts)

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64
CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [11]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 100

classifications_to_replace = classification_counts[classification_counts < cutoff_value].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)

application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [13]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values

X = application_df.drop(columns=['IS_SUCCESSFUL']).values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training data shape: {X_train.shape}, Training target shape: {y_train.shape}")
print(f"Testing data shape: {X_test.shape}, Testing target shape: {y_test.shape}")

Training data shape: (27439, 43), Training target shape: (27439,)
Testing data shape: (6860, 43), Testing target shape: (6860,)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
hidden_layer1_nodes = 80
hidden_layer2_nodes = 30

nn = tf.keras.models.Sequential()
input_features = X_train.shape[1]

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer1_nodes, input_dim=43, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_layer2_nodes, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

C:\Users\Alex\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           3,520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,981 (23.36 KB)

 Trainable params: 5,981 (23.36 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [22]:
# Train the model

X_train = np.array(X_train, dtype=np.float32)
X_test = np.array(X_test, dtype=np.float32)
y_train = np.array(y_train, dtype=np.float32)
y_test = np.array(y_test, dtype=np.float32)

history = nn.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1, validation_data=(X_test, y_test))

Epoch 1/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 768us/step - accuracy: 0.4975 - loss: 57903.6914 - val_accuracy: 0.4659 - val_loss: 49276.3555
Epoch 2/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 668us/step - accuracy: 0.5057 - loss: 34816.6680 - val_accuracy: 0.5341 - val_loss: 0.6916
Epoch 3/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5313 - loss: 0.6919 - val_accuracy: 0.5341 - val_loss: 0.6910
Epoch 4/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 627us/step - accuracy: 0.5335 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 5/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5315 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 6/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 630us/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 7/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5317 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 8/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5306 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 9/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - accuracy: 0.5311 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 10/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 631us/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 11/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 624us/step - accuracy: 0.5367 - loss: 0.6905 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 12/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - accuracy: 0.5294 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 13/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.5330 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 14/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5312 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 15/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5375 - loss: 0.6904 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 16/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 628us/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 17/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 18/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 625us/step - accuracy: 0.5354 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 19/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5351 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 20/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5364 - loss: 0.6906 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 21/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5296 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 22/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5350 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 23/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5310 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 24/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - accuracy: 0.5274 - loss: 0.6917 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 25/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.5340 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 26/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5341 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 27/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5340 - loss: 0.6909 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 28/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5343 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 29/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5263 - loss: 0.6918 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 30/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5317 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 31/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5341 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 32/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 643us/step - accuracy: 0.5327 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 33/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5371 - loss: 0.6904 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 34/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 35/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5363 - loss: 0.6906 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 36/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 631us/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 37/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5349 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 38/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5332 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 39/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 40/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 628us/step - accuracy: 0.5344 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 41/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5310 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 42/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - accuracy: 0.5322 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 43/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 632us/step - accuracy: 0.5338 - loss: 0.6909 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 44/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5329 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 45/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - accuracy: 0.5321 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 46/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 633us/step - accuracy: 0.5316 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 47/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5318 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 48/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5316 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 49/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5312 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 50/100

858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5319 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 51/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5360 - loss: 0.6906 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 52/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5334 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 53/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5298 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 54/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5373 - loss: 0.6904 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 55/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 648us/step - accuracy: 0.5298 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 56/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 684us/step - accuracy: 0.5349 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 57/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 658us/step - accuracy: 0.5329 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 58/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5326 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 59/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - accuracy: 0.5256 - loss: 0.6920 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 60/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5370 - loss: 0.6904 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 61/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 62/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5311 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 63/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - accuracy: 0.5298 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 64/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5314 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 65/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5346 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 66/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 635us/step - accuracy: 0.5284 - loss: 0.6916 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 67/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - accuracy: 0.5334 - loss: 0.6909 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 68/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5276 - loss: 0.6917 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 69/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 650us/step - accuracy: 0.5287 - loss: 0.6916 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 70/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 644us/step - accuracy: 0.5306 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 71/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5324 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 72/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - accuracy: 0.5356 - loss: 0.6906 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 73/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 640us/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 74/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5343 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 75/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - accuracy: 0.5301 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 76/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 670us/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 77/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 672us/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 78/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5356 - loss: 0.6907 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 79/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 666us/step - accuracy: 0.5307 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 80/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - accuracy: 0.5325 - loss: 0.6911 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 81/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 637us/step - accuracy: 0.5326 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 82/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5294 - loss: 0.6915 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 83/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5302 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 84/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 639us/step - accuracy: 0.5296 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 85/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 645us/step - accuracy: 0.5296 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 86/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 636us/step - accuracy: 0.5277 - loss: 0.6917 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 87/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 641us/step - accuracy: 0.5299 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 88/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 638us/step - accuracy: 0.5341 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 89/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 634us/step - accuracy: 0.5301 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 90/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 643us/step - accuracy: 0.5348 - loss: 0.6908 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 91/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 655us/step - accuracy: 0.5300 - loss: 0.6914 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 92/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 646us/step - accuracy: 0.5265 - loss: 0.6918 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 93/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - accuracy: 0.5281 - loss: 0.6916 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 94/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 648us/step - accuracy: 0.5384 - loss: 0.6902 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 95/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 647us/step - accuracy: 0.5332 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6909
Epoch 96/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 647us/step - accuracy: 0.5328 - loss: 0.6910 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 97/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 656us/step - accuracy: 0.5302 - loss: 0.6913 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 98/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 651us/step - accuracy: 0.5359 - loss: 0.6906 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 99/100

858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 652us/step - accuracy: 0.5291 - loss: 0.6915 - val_accuracy: 0.5341 - val_loss: 0.6908
Epoch 100/100
858/858 ━━━━━━━━━━━━━━━━━━━━ 1s 642us/step - accuracy: 0.5313 - loss: 0.6912 - val_accuracy: 0.5341 - val_loss: 0.6908

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

215/215 - 0s - 486us/step - accuracy: 0.6045 - loss: 0.6774
Loss: 0.6773536205291748, Accuracy: 0.6045189499855042

In [24]:
# Export our model to HDF5 file
nn.save('trained_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.